//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerformanceCounterHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PerformanceCounterHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiInstance performance counters categories need to have instanceName associated..
        /// </summary>
        internal static string CounterHelper_MultiInstanceNoInstanceNameErrorMessage {
            get {
                return ResourceManager.GetString("CounterHelper_MultiInstanceNoInstanceNameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal base counter for {0}.
        /// </summary>
        internal static string PerformanceHelper_BaseCounterDescription {
            get {
                return ResourceManager.GetString("PerformanceHelper_BaseCounterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        internal static string PerformanceHelper_BaseTypeNameAddon {
            get {
                return ResourceManager.GetString("PerformanceHelper_BaseTypeNameAddon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version supports internally the creation of base types, remove {0} from your code..
        /// </summary>
        internal static string PerformanceHelper_BaseTypeSupportedInternalErrorMessage {
            get {
                return ResourceManager.GetString("PerformanceHelper_BaseTypeSupportedInternalErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enumType cannot be null..
        /// </summary>
        internal static string PerformanceHelper_EnumTypeCannotBeNullErrorMessage {
            get {
                return ResourceManager.GetString("PerformanceHelper_EnumTypeCannotBeNullErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} needs to be enum type..
        /// </summary>
        internal static string PerformanceHelper_EnumTypeErrorMessage {
            get {
                return ResourceManager.GetString("PerformanceHelper_EnumTypeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum &apos;{0}&apos; needs to have a PerformanceCounterCategoryAttribute with category information..
        /// </summary>
        internal static string PerformanceHelper_EnumTypeNoPerformanceCounterCategoryAttributeErrorMessage {
            get {
                return ResourceManager.GetString("PerformanceHelper_EnumTypeNoPerformanceCounterCategoryAttributeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enumValue cannot be null..
        /// </summary>
        internal static string PerformanceHelper_EnumValueCannotBeNullErrorMessage {
            get {
                return ResourceManager.GetString("PerformanceHelper_EnumValueCannotBeNullErrorMessage", resourceCulture);
            }
        }
    }
}
