//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerformanceCounterHelper.Installer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PerformanceCounterHelper.Installer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: File is not well-formed or is not compatible with this version..
        /// </summary>
        internal static string Console_AssemblyNotCompatibleErrorMessage {
            get {
                return ResourceManager.GetString("Console_AssemblyNotCompatibleErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string Console_Error {
            get {
                return ResourceManager.GetString("Console_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: File doesn&apos;t exists..
        /// </summary>
        internal static string Console_FileDoesNotExistErrorMessage {
            get {
                return ResourceManager.GetString("Console_FileDoesNotExistErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: File full path required..
        /// </summary>
        internal static string Console_FileFullPathIsRequiredErrorMessage {
            get {
                return ResourceManager.GetString("Console_FileFullPathIsRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: File was not found..
        /// </summary>
        internal static string Console_FileNotFoundErrorMessage {
            get {
                return ResourceManager.GetString("Console_FileNotFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: File was found, but couldn&apos;t be loaded..
        /// </summary>
        internal static string Console_FileNotLoadedErrorMessage {
            get {
                return ResourceManager.GetString("Console_FileNotLoadedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found Types:.
        /// </summary>
        internal static string Console_FoundTypesTitle {
            get {
                return ResourceManager.GetString("Console_FoundTypesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the assembly from which Performance Counters would be installed / uninstalled.
        ///
        ///    PerformanceCounterHelper.Installer.exe [/U] [Assembly]
        ///
        ///    Params:
        ///        [/U]: uninstall option
        ///
        ///    Examples:
        ///        PerformanceCounterHelper.Installer.exe assembly1.dll
        ///        PerformanceCounterHelper.Installer.exe /u assembly1.dll.
        /// </summary>
        internal static string Console_Help {
            get {
                return ResourceManager.GetString("Console_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing Type &apos;{0}&apos; --&gt;.
        /// </summary>
        internal static string Console_InstallingTypeMessage {
            get {
                return ResourceManager.GetString("Console_InstallingTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None..
        /// </summary>
        internal static string Console_NoneTypesFound {
            get {
                return ResourceManager.GetString("Console_NoneTypesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Console_OK {
            get {
                return ResourceManager.GetString("Console_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1}.
        /// </summary>
        internal static string Console_PerformanceCountersCategoryFoundInformation {
            get {
                return ResourceManager.GetString("Console_PerformanceCountersCategoryFoundInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PerformanceCounterHelper.Installer v{0}.
        /// </summary>
        internal static string Console_Title {
            get {
                return ResourceManager.GetString("Console_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling Type &apos;{0}&apos; --&gt;.
        /// </summary>
        internal static string Console_UninstallingTypeMessage {
            get {
                return ResourceManager.GetString("Console_UninstallingTypeMessage", resourceCulture);
            }
        }
    }
}
